"""initial schema

Revision ID: f790a40c397b
Revises: 
Create Date: 2026-03-13 10:59:23.642595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f790a40c397b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('profile_type', sa.String(length=64), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('raw_source', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_seed_run_id'), 'stores', ['seed_run_id'], unique=False)
    op.create_table('synthetic_validation_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_validation_failures_seed_run_id'), 'synthetic_validation_failures', ['seed_run_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('home_store_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=32), nullable=False),
    sa.Column('price_sensitivity', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('occasion_affinity', sa.JSON(), nullable=False),
    sa.Column('style_vector', sa.JSON(), nullable=False),
    sa.Column('size_preferences', sa.JSON(), nullable=False),
    sa.Column('channel_preference', sa.String(length=32), nullable=False),
    sa.Column('pii_token', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['home_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_home_store_id'), 'customers', ['home_store_id'], unique=False)
    op.create_index(op.f('ix_customers_seed_run_id'), 'customers', ['seed_run_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('margin_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inventory_qty', sa.Integer(), nullable=False),
    sa.Column('objective_weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('inventory_qty >= 0', name='ck_products_inventory_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_seed_run_id'), 'products', ['seed_run_id'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('store_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('sell_through', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('aov', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_run_id', 'store_id', 'metric_date', name='uq_store_daily_metric_run_store_date')
    )
    op.create_index(op.f('ix_store_daily_metrics_seed_run_id'), 'store_daily_metrics', ['seed_run_id'], unique=False)
    op.create_index(op.f('ix_store_daily_metrics_store_id'), 'store_daily_metrics', ['store_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('occasion', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_orders_subtotal_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_seed_run_id'), 'orders', ['seed_run_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_table('product_embeddings',
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('seed_run_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('vector_id', sa.String(length=128), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_run_id'], ['synthetic_runs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_embeddings_seed_run_id'), 'product_embeddings', ['seed_run_id'], unique=False)
    op.create_index(op.f('ix_product_embeddings_store_id'), 'product_embeddings', ['store_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_product_embeddings_store_id'), table_name='product_embeddings')
    op.drop_index(op.f('ix_product_embeddings_seed_run_id'), table_name='product_embeddings')
    op.drop_table('product_embeddings')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_seed_run_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_store_daily_metrics_store_id'), table_name='store_daily_metrics')
    op.drop_index(op.f('ix_store_daily_metrics_seed_run_id'), table_name='store_daily_metrics')
    op.drop_table('store_daily_metrics')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_seed_run_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_seed_run_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_home_store_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_synthetic_validation_failures_seed_run_id'), table_name='synthetic_validation_failures')
    op.drop_table('synthetic_validation_failures')
    op.drop_index(op.f('ix_stores_seed_run_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('synthetic_runs')
    # ### end Alembic commands ###
